# profiles.yml
meu_projeto_perfil:  # Este nome deve ser igual ao 'profile:' no seu dbt_project.yml
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: tcc-bigdata-486203  # <--- Coloque o ID do seu projeto GCP
      dataset: analytics_silver     # Dataset padrão onde o dbt criará as tabelas
      threads: 4
      keyfile: /app/google_creds.json # Caminho INTERNO do container Docker
      location: US                  # Ou 'southamerica-east1' (São Paulo) se preferir
      priority: interactive
      retries: 1